### ISSUE TITLE
Implement setAffidavitTemplate

### ISSUE THREAD

**Issue by cwisdo** [TrustTheVote-Project/ABC-backend#105]

**Comment by cwisdo** [comment]
Do we want to do this via the the admin-ui?

**Comment by trustthevote** [comment]
No from UI. It is part of deployment to put the locally appropriate template file in the right place. Deploy auto should deploy the one from the repo, but in a real deploy, the deployer would replace that file with the real one. Local election admins don't get to change this template per election. Usually it is state election office that is permitted to issue a new affidavit form.

And since our default is in the repo, and the app is already getting it from the Provisioner (right?) I am not sure what else there is to do, maybe deploy automation, certainly deploy doc.

**Comment by cwisdo** [comment]
Okay. This is already part of the automated deploy. 
So marking this as resolved.
